### ISSUE TITLE
Extension parameter don't work.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#110]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ x] Are you running the latest version?
- [ x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description
Parameters given to piral extensions are not working.
I've reproduced the bug here:
https://github.com/luckyluggi/piral_extensions_and_aimages

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
The origin of the bug is the blazor serialization. When going from .NET to JS blazor implicitly does a PascalCase to camelCase conversion, however, in this cycle we did not change the deserialization option. Therefore, the JSON deserializer ignores the lowercase `value` and does not populate `Value` for the given example.

This is fixed (and more options, e.g., incl. fields, ignoring read-only properties etc.) are also included making the conversion better / more reliable than beforehand.
