### ISSUE TITLE
Components with the [PiralComponent] attribute should support adding @typeparam

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#113]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ x] Are you running the latest version?
- [ x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description
See an example here (Problem nr. 1 in the Readme.md file):
https://github.com/luckyluggi/piral_meeting_examples

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Well, this is not a bug, but actually how its supposed to be.

`PiralComponent` decorated components are directly exposed to Piral and therefore can be mounted from anywhere (e.g., from React). Since they are mounted / exposed to JS there is no way to have them mounted with type parameters. As such only non-generic components can be decorated as `PiralComponent`.

What we'll do is to actually skip generic components and print a warning - this is much nicer than the current behavior.

This will also be added to the documentation.

(It would be simple to also instantiate generic components, however, since we don't have the type yet (and for the actual instantiation will never have one - as this is, as explained, done from JS) it is impossible to do right)
