### ISSUE TITLE
When Debugging a pilet with an updated dependency this new version of the dependency should be used by all pilets.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#121]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

If we update a nuget package  in a pilet and debug this pilet corrently the old version is still used if the same nuget package is already loaded by another pilet. It would be great if the new version is used at least while debugging.

## Background

Currently i need to update the package in all pilets using it and run them all locally.

## Discussion

This would make local dev easier on one hand. On the other hand it could lead to problems, because the pilet might not work when its released because in prod it does still use the old version.

So maybe it would be better to always use the newest version?
Or maybe it should be configurable?

**Comment by FlorianRappl** [comment]
Yes I think right now we don't do any semver or so comparison on the .NET dependencies.

This should be definitely done.

**Comment by FlorianRappl** [comment]
This is fixed with the latest preview and will be part of the v9.

In general there is new model for dependencies; by default pilets will have dependencies *only* assigned to them / their execution context. As a consequence the execution context of a pilet can / will be unloaded when the pilet is unloaded. Therefore, changed dependencies will also change when a pilet changes (= unload / load again).

However, that also implies that dependencies are no longer shared (by default). With v9 there will be new methods of sharing certain dependencies, but by default no dependencies (besides the "core deps" e.g. Blazor and Piral runtime DLLs) are shared.

We will document / specify this separately.
