### ISSUE TITLE
Enable cjproject includes

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#124]
Since most of our piral config is the same for all our pilets we'd like to set it up in an xml file thats the included into the csproj files of all our pilets. This should be possible with partial csproj files described [here](https://alex-v.blog/2019/04/13/partial-csproj-files-simplify-your-nuget-dependencies/) But piral does not yet recognize included files.

I've made a little project to demo the problem:
https://github.com/luckyluggi/piral_blazor_csproj_include

**Comment by FlorianRappl** [comment]
Yeah not sure if we can tackle it. We only use MSBuild to process this and if its not out of the box transported by MSBuild we cannot introduce it.

If somebody wants to tackle this it's fine, but since we have no knowledge in this one it is a pass for the moment (if you want to get involved here feel welcome).

Furthermore, there could be a different mechanism similar to the "extends" field of, e.g., of a tsconfig. I guess such an approach would be easier in the sense that it anyway is supported from MSBuild by default and the resolution / capturing of the file is custom anyway.

**Comment by FlorianRappl** [comment]
Any update on this one? As written MSBuild does not do this merging and I am not sure how "official" this is (the MS docs don't mention this to my knowledge).

**Comment by luckyluggi** [comment]
The import element is now documented here:
https://learn.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2022

I've updated the example project.
The imports are now recognized and the project is building.
The only thing i could find that does not work is the setting for `<ConfigFolder>.piralconfig</ConfigFolder>` is not recognized anymore.

**Comment by FlorianRappl** [comment]
This should be fixed in v17 - with the constraint that conditional imports won't work (they will always be taken, independent of the condition).
