### ISSUE TITLE
PiralQueryParameter availablility

### ISSUE THREAD

**Issue by ghost** [FlorianRappl/Piral.Blazor#134]
# Bug Report

## Environment Details and Version

- "blazor": "[7.0.10]"
- "piral": "[1.4.3]"
"Piral.Blazor.*" Version="7.0.10"

## Description

The behavior of the parameters is inconsistent.
PiralRouteParameter is already available in _OnInitialized()_.
PiralQueryParameter, on the other hand, is only available in _AfterRender(bool)_.

## Steps to Reproduce

1. create Pilet
2. add propertiey with PiralQueryParameterAttribute within a page

## Expected behavior

PiralQueryParameter-Value is available in _OnInitialized()_.

## Actual behavior

PiralQueryParameter-Value is available in _AfterRender(bool)_.

## Addendum

Our Team need to know, how to debug Piral.Blazor.Core project.

**Comment by FlorianRappl** [comment]
Internally there is no difference between the two - if one is not available then this is up to the NavigationManager of Blazor; so nothing we will / can do here on a first glance.

The report is also missing a proper MWE - if you want us to take a look you'd need to supply one. Many thanks!

**Comment by FlorianRappl** [comment]
Is this still relevant? As mentioned from Piral both are treated the same, the main difference is within Blazor / under the hood. One is known from the beginning (we know the path we come from; so we know all the path parameters) while the other might be known only later / when the NavigationManager "sees" it.

I don't think we can solve this in general (because the underlying question is "when does the query string exist"); so I'd close for this now until we have relevance / a full example.
