### ISSUE TITLE
Single entrypoint per pilet

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#146]
Currently we can create 1 Component decorated with the PiralAppRoot-Attriubute. This is a single entryfile for all Pilets loaded in the instance.

It would be great to have one entry file per pilet in addition to that.
This way a pilet could manage its in own state in a single component wrapping all other Components.

I know that this can be done via services injected into components via DI, but when using services components have to bee hooked to OnChange events of those services manualy.
It would be much more convenient to handle state in a component and cascade it down to all children.

I have created an example project here:
https://github.com/luckyluggi/piral_example_for_multiple_issues

When you open the `/shop` page and add some products to the cart, you can see the red card being updated , but the green card is not.
The red cart is created using a Service injected via DI.
The green cart can obviously not work, since the state component can currently not be inseted in a single place.

To see the green cart in action you may start the standard blazor app in `BlazorApp\BlazorApp.csproj` where the `<GreenCartContext>` is included inside the App.razor file and therefor it works.

I don't know if this would be possible, but it'd be a good way to manage state across all components of a pilet. 
If someone has an even better way to manage such state please tell me.

**Comment by FlorianRappl** [comment]
> It would be great to have one entry file per pilet in addition to that.

We already have that. This mechanism is called a provider, and its one per pilet.
https://github.com/smapiot/Piral.Blazor?tab=readme-ov-file#provider-components

Note that for a state container you should use DI, which is per pilet already and works to inject something into all relevant pilets.

Technically it won't be possible to have the root per pilet - it's one root per app (that's why its a root) and that already is complicated / not ideal as usually components are somewhere else. (we go to great lengths to still make this possible, but its not intended to be abused).
