### ISSUE TITLE
Images from isnide the wwwroot folder can not be referenced.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#95]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version?
- [ ] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description

When i try to reference an image from inside the wwwroot folder it is not shown.
Example:
<img src="/img/logo.png" />
The image does exist in wwwroot/img/logo.png but is not shown.

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Well, this is not really a bug. The reference needs to be done via the pilet's local path - you reference just *some* path.

Changed to enhancement, as what is needed is a function that can be used to generate paths using the pilet's local path (in JS this is done either implicitly by using imports / require statements or explicitly by using the pilet's meta `basePath`).

**Comment by FlorianRappl** [comment]
Added and documented helper `IPiletService`, which can be injected into any component.

**Comment by FlorianRappl** [comment]
As a bit of background on this:

1. It was supported to some degree - we made some magic to replace local resource URLs for their pilet-specific URLs, however, this only works for some attributes (e.g., `img.src`) and was only done on first rendering (i.e., if a component would first show something else, then wants to show, e.g., after a button click, an image, this would not have worked).
2. There was a bug that standalone pilets would not have the mentioned (1) magic applied.

The fix now does the following:

1. We hereby deprecate the previous mechanism. Since this mechanism is part of `piral-blazor` we will not remove it for now, but we will actually make it optional. Future (v4 and higher) versions will switch into a mode where the magic won't be applied.
2. Standalone pilets now receive the same config and do now work the same.
3. With the new `IPiletService` the URLs can be formed explicitly. Therefore, correct URLs are no longer restricted to first-time rendering or certain attributes, but can always be applied.

The service is documented in the README:

👉 https://github.com/smapiot/Piral.Blazor/#standard-pilet-service
