### ISSUE TITLE
Include script files in referenced packages or RCLs

### ISSUE THREAD

**Issue by tillr** [FlorianRappl/Piral.Blazor#99]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

In Blazor WASM, it is sometimes necessary to reference static JS assets defined in imported NuGet packages or referenced Razor Class Libraries. One example is `Microsoft.Authentication.WebAssembly.Msal`, which provides a static script file named `AuthenticationService.js` which needs to be referenced in the HTML body of `wwwroot/index.html` like so:

```
<script src="_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js"></script>
```

The same applies to any shared Razor Class Libraries referenced by a pilet, which may also provide static JS files to be used in the same fashion as described above.

Piral.Blazor should support this pattern and provide a way to reference these assets.

## Background

As of now, there is no obvious way to reference static JS files within RCLs or NuGet packages from within a Blazor pilet.

**Comment by FlorianRappl** [comment]
So we'll bring this to `v4` with the following technique: The `setup.tsx` will now also get another parameter that is `addScript`. Previously:

```tsx
export default function setup(api) {
  // do some setup stuff, e.g., `api.registerMenu` here
}
```

Now:

```tsx
export default function setup(api, addScript) {
  addScript("_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js");
  // do some setup stuff, e.g., `api.registerMenu` here
}
```

It would be exactly the same URLs that you'd use otherwise - only presented here. Under the hood, we'll add the scripts to the DOM and make sure to actually await / monitor their loading. If they fail to load then the pilet will actually fail to load.
